import { Pair } from '@/shared/lib/utils';

type GET_SNOWFLAKE_MESSAGE = {
  key: `SNOWFLAKE/GET`;
};
type GET_SNOWFLAKE_RESPONSE = boolean;
type GET_SNOWFLAKE = Pair<GET_SNOWFLAKE_MESSAGE, GET_SNOWFLAKE_RESPONSE>;

type TOGGLE_SNOWFLAKE_MESSAGE = {
  key: `SNOWFLAKE/TOGGLE`;
};
type TOGGLE_SNOWFLAKE_RESPONSE = void;
type TOGGLE_SNOWFLAKE = Pair<TOGGLE_SNOWFLAKE_MESSAGE, TOGGLE_SNOWFLAKE_RESPONSE>;

type SNOWFLAKE_PAIRS = {
  GET_SNOWFLAKE: GET_SNOWFLAKE;
  TOGGLE_SNOWFLAKE: TOGGLE_SNOWFLAKE;
};

export type { SNOWFLAKE_PAIRS };
