import { Pair } from '@/shared/lib/utils';

type GET_FIREWORK_MESSAGE = {
  key: `FIREWORK/GET`;
};
type GET_FIREWORK_RESPONSE = boolean;
type GET_FIREWORK = Pair<GET_FIREWORK_MESSAGE, GET_FIREWORK_RESPONSE>;

type TOGGLE_FIREWORK_MESSAGE = {
  key: `FIREWORK/TOGGLE`;
};
type TOGGLE_FIREWORK_RESPONSE = void;
type TOGGLE_FIREWORK = Pair<TOGGLE_FIREWORK_MESSAGE, TOGGLE_FIREWORK_RESPONSE>;

type FIREWORK_PAIRS = {
  GET_FIREWORK: GET_FIREWORK;
  TOGGLE_FIREWORK: TOGGLE_FIREWORK;
};

export type { FIREWORK_PAIRS };
